version: "3"

services:
  app:
    container_name: profiles-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:127.0.0.1:8080
    volumes:
      - .:/app
    restart: unless-stopped
